<a href="https://colab.research.google.com/github/Marshud/ml-classes-01/blob/main/ML_DummyVariablesAndHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('homeprices.csv')
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [ ]:
dummies = pd.get_dummies(df.town)
dummies

    monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [ ]:
merged = pd.concat([df, dummies], axis='columns')
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [ ]:
final = merged.drop(['town', 'west windsor'], axis='columns')
final

    area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
X = final.drop('price', axis='columns')
X

    area  monroe township  robinsville
0   2600             True        False
1   3000             True        False
2   3200             True        False
3   3600             True        False
4   4000             True        False
5   2600            False        False
6   2800            False        False
7   3300            False        False
8   3600            False        False
9   2600            False         True
10  2900            False         True
11  3100            False         True
12  3600            False         True

In [ ]:
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [ ]:
model.fit(X, y)

LinearRegression()

In [ ]:
model.predict([[2800, 0, 1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

In [ ]:
model.predict([[3400, 0, 0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.66845839])

In [ ]:
model.score(X, y)

0.9573929037221872

In [ ]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [ ]:
X = dfle[['town', 'area']].values # This produces a 2D rraye
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [ ]:
y = dfle.values
y

array([[     0,   2600, 550000],
       [     0,   3000, 565000],
       [     0,   3200, 610000],
       [     0,   3600, 680000],
       [     0,   4000, 725000],
       [     2,   2600, 585000],
       [     2,   2800, 615000],
       [     2,   3300, 650000],
       [     2,   3600, 710000],
       [     1,   2600, 575000],
       [     1,   2900, 600000],
       [     1,   3100, 620000],
       [     1,   3600, 695000]])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder()

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'categorical_features'

In [ ]:
ohe.fit_transform(X).toarray()

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Re-create X from dfle to ensure we have the original labeled data for town and area
# as X was last defined as dfle[['town', 'area']].values
X_transformed = dfle[['town', 'area']].values

# The ColumnTransformer takes a list of (name, transformer, columns) tuples
# Here, we apply OneHotEncoder to the first column (index 0) and 'passthrough' the second column (index 1)
ct = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(), [0]), # Apply OneHotEncoder to the 'town' column (index 0)
        ('passthrough', 'passthrough', [1]) # Keep the 'area' column (index 1) as is
    ],
    remainder='drop' # Drop any other columns not specified (though not strictly necessary here as we specify all)
)

# Apply the transformation
X_new = ct.fit_transform(X_transformed)

# Display the transformed X
print("Original X:")
print(X_transformed)
print("\nTransformed X with OneHotEncoder on 'town' and 'area' passed through:")
print(X_new)